# Generated by Django 4.2.5 on 2024-06-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertext',
            name='last_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
